### ISSUE TITLE
ETL of vital status and date of vital status from NAACCR

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#111]
Depends on #110

**Comment by sratwani** [comment]
This is dependent on the modeling task. A decision is pending on whether this should be a part of the vital status. @rimusia is working on it and will get back to us on an update.

**Comment by sratwani** [comment]
Per discussion on 12/11, This issue is related to the gap (person table and observation period) between what the ETL produces and what is needed to make the plots. There is a stand-alone script that handles the gaps, but each organization had their own script and we just need to standardize this. We could also incorporate the script in the ETL and set a flag for one-off solutions like Tufts where NAACCR data sits on its own and is not connected to their EHR. The question on whether we want to include this task in the first milestone was answered by the team as needing it for the first milestone.

**Comment by sratwani** [comment]
Per discussion on 12/11, This issue is related to the gap (person table and observation period) between what the ETL produces and what is needed to make the plots. There is a stand-alone script that handles the gaps, but each organization had their own script and we just need to standardize this. We could also incorporate the script in the ETL and set a flag for one-off solutions like Tufts where NAACCR data sits on its own and is not connected to their EHR. The question on whether we want to include this task in the first milestone was answered by the team as needing it for the first milestone.
