### ISSUE TITLE
Determine modeling and vocabulary support for the representation of other 'Disease Episodes' beyond 'Disease First Occurrence'.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#123]
- Recurrence
- Progression
- Stable Disease
- Remission
- End of life event

And so on.

**Comment by mgurley** [comment]
Review:

- NAACCR
- Check m-code, Cotta, Flatiron
- Talk to Pedram about local recurrences vs. metastatic vs. primary

**Comment by mgurley** [comment]
See here for how mCode does it: http://standardhealthrecord.org/guides/mcode/#Outcomes

**Comment by cgreich** [comment]
Sounds to me like we need:

> Remission
> Stable Disease
> Progression
> Recurrence

And the convention is that after the statement of any of these three it stays the same, until another one overwrites it. We could also check for some logic. For example, you cannot have Remission - Progression - Remission, unless there is a treatment in between.

> end of life event

Not sure what that would be. We may want to think about "palliative care".

> how mCode does it

Looks like they are using "physician judgment", whatever that is.

**Comment by cgreich** [comment]
Actually, let's close this discussion and move it to [144](https://github.com/OHDSI/OncologyWG/issues/144).

**Comment by mgurley** [comment]
See NAACCR variables here:
http://datadictionary.naaccr.org/?c=10#1880
http://datadictionary.naaccr.org/?c=10#1861

**Comment by mgurley** [comment]
> Actually, let's close this discussion and move it to [144](https://github.com/OHDSI/OncologyWG/issues/144).

@cgreich 'Response to Treatment' is different than 'Disease Episode/Status'.  So I don't hink we should close this dicussion.  We need to model 'Disease Episodes/Status' for sure and decide if we want to also model 'Response to Treatment'.   My guess is that we don't want to model 'Response to Treatment' because the data would only ever be avaialble for Study patients.

**Comment by crabcakeworld** [comment]
@mgurley 
I uploaded a file [here](https://github.com/OHDSI/OncologyWG/blob/master/documentation/Recurrence%20concepts%20that%20need%20to%20be%20created.xlsx)
that specifies all the concepts needs to be created to complete this task. i have not included all the relationships yet. Once all the concepts are ironed out, I will specify the relationships.

**Comment by cgreich** [comment]
> 'Response to Treatment' is different than 'Disease Episode/Status'. So I don't think we should close this discussion.

Well, that's what you agreed to in #144. :)

Look: Obviously there is a response to treatment or not. The question is is that data, or is that result. And I would strongly suggest to go with @jeremywarner and not model that into the data, partially because it is almost impossible, partially because there is no clear set of concepts, partially because we shouldn't mix input and output of research.

> complete this task

What is this list? Everything that has the string "recur" in it? It's a good list. I would map them to the actual lesion, and put indeed "Recurrence" into the Episode.

**Comment by mgurley** [comment]
@cgreich 

I agree that we don't want to model 'Response to Treatment' into the data.  We should close #144 with the answer "No".  But we do need to finish modeling 'Disease Episode'.  This is a list of possible values from the NAACCR Variable 'RECURRENCE TYPE--1ST'. See here:

http://datadictionary.naaccr.org/?c=10#1880

We definitely don't want to use it as our standard 'Disease Episode' concepts.  It is too fine-grained and clunky.  But we do need to create mappings from these possible values to our standard 'Disease Episode' concepts.  So that NAACCR recurrence data can be ingested into OMOP.  These are our current standard disease episode: 

- Disease First Occurrence
- Disease Recurrence
- Disease Remission
- Disease Progression

I believe we are missing the following:

- 'Disease Metastasis'

And maybe: 

- 'Disease Relapse'

We also need to define what the difference is between 'Disease Recurrence' and 'Disease Progression'.  And decide if we want to keep our 'Disease Episode' concepts as home-grown OMOP-generated or if we want to try to bind and source them from an authoritative source.  Perhaps what mCode is using:

http://hl7.org/fhir/valueset-condition-clinical.html

Or try to do the normal routine in looking in the SNOMED forest.  Or find something else.

**Comment by crabcakeworld** [comment]
I use the word 'Metastasis' instead of 'Disease Metastasis' because unlike first occurrence, progression, remission, and recurrence which applies to many other diseases besides cancer, metastasis only applies to cancer. If we are going to use the Episode table for other diseases, e.g., SLE, the concept of metastasis does not really apply. So maybe we can call it 'Tumor Metastasis' or 'Cancer Metastasis'.

**Comment by jeremywarner** [comment]
For response to treatment you need to decide which approach to adopt, or both:

Response relative to baseline: this is the traditional approach – patient presents with a tumor that measures x cm, and each time it is re-measured, the response is compared to the baseline. If it disappears = complete response, if it shrinks by yy %, partial response, if it stays the same, stable disease, if it gets zz % bigger, progression. These are the RECIST criteria, although many cancer subtypes have their own nuances (CCyR, CMR, etc).

Response relative to prior: this is the PRISSMM approach – for each serial encounter, is the tumor bigger, smaller, or the same as the previous encounter (or indeterminate)? Unlike the RECIST approach, this one is pretty much generalizable to any cancer subtype.

Best,
Jeremy

Jeremy L. Warner MD, MS, FAMIA, FASCO
Associate Professor of Medicine and Biomedical Informatics
Associate Editor, JCO Clinical Cancer Informatics
Deputy Editor, HemOnc.org
2220 Pierce Avenue | 777 PRB | Nashville, TN  37232-6307

Jennifer Bauer
Interim Administrative Assistant
jennifer.m.bauer@vumc.org
615-875-4547

**Comment by cgreich** [comment]
Friends:

Looks like we are on the home stretch here (apart from the exact naming). 

> For response to treatment you need to decide which approach to adopt

I'd say the traditional, since the PRISSMM approach requires a resolution of timing and details we mostly won't have. Plus, we are not diagnosing or double guessing the diagnosis of patients, we are just capturing established facts in a standardized manner.

**Comment by sratwani** [comment]
This task is complete and was presented at the 2020 Oncology Tutorial.
