### ISSUE TITLE
Define maturity model categories that specify readiness for adoption of our ETLs, CDM schema, algorithms, mappings, study packages,etc.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#168]
At the 10/17 Oncology Development Subgroup meeting @AEW0330 suggested we apply a maturity model to our ETL code bases.  So people have an idea the level of quality to expect.

**Comment by sratwani** [comment]
@mgurley is this the responsibility of the Development Subgroup. I understood from the call that Andrew will work with Chan and Martin on this.

**Comment by mgurley** [comment]
It kind of cuts across all the groups. So I think this is OK to live with the Development Group.

However, I think you are mixing this with #114.  That is where @AEW0330 and @patelm9 need to work with @schuemie  and @chandryou

**Comment by chandryou** [comment]
We developed R package for automated ETL process for Korean claim data, which is available at [OHDSI github](https://github.com/OHDSI/ETL---Korean-NSC/tree/master/etlKoreanNSC).

**Comment by AEW0330** [comment]
The categorization of ETL maturity is a Development Subgroup issue. 
That issue, as Mike says, is separate from developing support for best practices in the development and registration of study packages. Those are practices we want to support in a standardized way for the development and registration of study packages should be tagged with Research/Outreach labels. See my recent email exchange on that with Marc Suchard.

I gave strawman definitions for the maturity categories for ETLs in an email. I'm copying them below. I think it is for the development group and especially Mike and Robert to accept, reject, ratify, alter these as they see fit. 

**PROPOSAL**: OHDSI should adopt a practice of categorizing the maturity of proposed products so that interested parties can assess their readiness for adoption.
The categories are a variant of a slightly more complex set recently proposed to support open science at CTSA hubs in the CD2H consortium. That proposal had software maturity in mind.
I think a transparent marker of maturity would be useful for several OHDSI products including ETL's, expansions/alterations of the CDM, phenotypes, etc.
Lee, Christian, and Clair (CCed) indicated some interest in this and there was agreement to try implementing for proposed CDM changes.

Here is how the proposed categories might be defined for ETLs produced by the Onc Development WG for each source (NAACCR, general purpose EHR, oncology-specific EHR, CDISC STDM...) :

- **Registered**: Has been added to the OHDIS Oncology WG GitHub

- **Verified**: Meets specified documentation and coding requirements - Documentation, Unit tests, DQ rules, other?

- **Validated**: Has been found to work as intended at one site as assessed by a prespecified quantifiable performance metric

- **Benchmarked**: Performance metrics from multiple community members is available for use to assess relative performance

Mike, Robert, and Anastasios should be the judge of:

- _Is some categorization of maturity/readiness for adoption a useful practice to follow in the Development WG's ETLs?_

- _Does this set of categories and definitions seem close to what's needed?_

- _What should be added, further specified, changed?_

- _How would the assignment of categories be managed and made publicly available?_

**Comment by sratwani** [comment]
@AEW0330 is the idea to gather the information/categories you proposed above in the form of a table and publishing it somewhere on the OHDSI website? Who is the audience of this type of information?

**Comment by mgurley** [comment]
Robert's new template will handle this.
