### ISSUE TITLE
Evaluation of Nebraska Lexicon

### ISSUE THREAD

**Issue by sratwani** [OHDSI/OncologyWG#179]
Based on the 10/22 Leadership Subgroup discussion, there is a need to perform an evaluation of Nebraska Lexicon to identify gaps, propose a solution that will work for them and expedite the process of aligning NAACCR and CAP.

**Comment by sratwani** [comment]
Andy from IMO is reviewing this for the breast cancer use case. Rimma to send Andy the data dictionary for breast cancer.

**Comment by ekorchmar** [comment]
After the most recent review, it looks like Nebraska Lexicon is (at least nominally) concordant with SNOMED international release. It works in the same way as all SNOMED editions do.

However, we found several issues inside of current release version that suggest that release files were not validated.

1. Some Condition concepts are made descendants of Navigational Concepts. [Navigational concepts](https://confluence.ihtsdotools.org/display/DOCGLOSS/Navigation+hierarchy) are not intended to have direct descendants among concepts from other hierarchies; navigational concepts have separate hierarchy that is separated from conventional 'Is a' links.

**How we solved it**: These links are preserved as given in OMOP CDM, but they are ignored for purposes of building standard hierarchy. We leave it to source to replace/correct them.

2. One attribute-relation link existed in reversed dublicate.
113727004	Vancomycin resistant enterococcus (organism)	246075003	Causative agent (attribute)	13110001000004105	Vancomycin resistant enterococcus urine (finding)
13110001000004105	Vancomycin resistant enterococcus urine (finding)	246075003	Causative agent (attribute)	113727004	Vancomycin resistant enterococcus (organism)

It possibly shows that some changes were made manually without following validation. Organism concepts can't normally have 'causative agent' relationships.

**How we solved it**: During ingestion, first link was skipped. Automatic filtration of erroneus links was implemented.

3. Concepts that were recently inactivated in SNOMED are still active in Nebraska Lexicon due to version mismatch.

**How we solved it**: Concepts, that are deactivated in the following versions, are never standard in Nebraska to discourage their use. Where possible, mappings to new replacement concept in international SNOMED is built.

Current state:
Nebraska Lexicon is fully processed and moves to be released in the next couple of days, following urgent  SNOMED march release. We are prepared to monitor feedback and fix newfound errors. Common hierarchy with SNOMED works as intended.

**Comment by sratwani** [comment]
Per comments above, this issue can be closed.

**Comment by sratwani** [comment]
Per comments above, this issue can be closed.
