### ISSUE TITLE
Truncate the the population of naaccr_data_points_tmp.naaccr_item_value to 255 characters. 

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#209]

**Comment by sratwani** [comment]
The issue with the field type should be rectified on the R parser side, not the ETL. Varchar(max) translates to a TEXT field in postgres which causes large efficiency issues, so we need to use VARCHAR(255). Rather than reclassify all those fields to varchar(max), we need to have the data input of the naaccr_item_value not be over 255 chars. A quick fix would be to truncate that field, there is logic you can pillage to do so on line 291.
