### ISSUE TITLE
Change all BIGINT to INT

### ISSUE THREAD

**Issue by rtmill** [OHDSI/OncologyWG#215]
Robert: 
"Christian : Did we revert back to INT for all concept_id fields? I remember a push to make them all BIGINT but the new documentation shows INT. "

Christian:
"Yeah. All the DDL types are minima. You can always go bigger. Right now, INT gives us a little more than 2 Billion concept IDs. All vocabs together need around 5M. So, we are still good for quite a while."

**Comment by mgurley** [comment]
@rtmill 
This is already done See #213.   If you agree, can you close this issue?

**Comment by rtmill** [comment]
Lots of BIGINT still in there. I just made a pull request for it though.

**Comment by mgurley** [comment]
@rtmill 
BIGINT is appropriate for clinical primary keys like person_id, visit_occurence_id, procedure_occurrence_id.   The issue was that BIGINTs were also applied to the '_concept_id' fields.  See the latest OMOP CDM SQL to see where BIGINT is used and where it is not nused

https://github.com/OHDSI/CommonDataModel/blob/master/PostgreSQL/OMOP%20CDM%20postgresql%20ddl.txt

**Comment by rtmill** [comment]
Oh ok I see now. Will amend the pull request.
