### ISSUE TITLE
Mapping of NAACCR CS_CZ to standard vacabulary

### ISSUE THREAD

**Issue by zhanghansi** [OHDSI/OncologyWG#304]
Dear OHDSI cancer registry team,

I'm working on an ETL which trying to convert our cancer registry data into OMOP.  

When I working the CS_SZ variable, I realized that its value set is so complicated, each type of cancer has its own value site to represent cancer size.  When you doing ETL, did u build a data dictionary for mapping, I could not find any related process in the SQL you provided.  Any suggestion will be appreciated. Thx!

**Comment by dimshitc** [comment]
Hi @zhanghansi 
Can you please elaborate on CS_SZ variable?

**Comment by zhanghansi** [comment]
For example, 993 described as "less than 3 cm," or "greater than 2 cm," or "between 2 cm and 3 cm".  After I checking the value set, i realized that each type of a cancer has a specific value (standard term) for 993.  For example "melanoma_tongue_anterior@2800@993" (concept id: 35929028), "lymphoma_ocular_adnexa@2800@993" (concept id: 35936911).  there are around 144 of them.     I can elaborate these values and mapping them locally, just wondering who u realized this variable in your ETL so that we can use as reference.

**Comment by dimshitc** [comment]
I see. That's a known issue. It occurs because of the NAACCR original structure. It treats each schema independently.
Here's the list of schemas https://staging.seer.cancer.gov/cs/list/02.05.50/
and there's is one example melanoma_tongue_anterior@280
https://staging.seer.cancer.gov/cs/input/02.05.50/melanoma_tongue_anterior/size/?breadcrumbs=(~schema_list~),(~view_schema~,~melanoma_tongue_anterior~)
and another 
lymphoma_ocular_adnexa@2800 
https://staging.seer.cancer.gov/cs/input/02.05.50/lymphoma_ocular_adnexa/size/?breadcrumbs=(~schema_list~),(~view_schema~,~lymphoma_ocular_adnexa~)
as you can see, the list of values is slightly different, thus in a first version of OMOP NAACCR we treated each value separately.
 We still need to dedup these.
@mik-ohdsi, @cgreich can we plan the NAACCR dedup and improvement work.

**Comment by cgreich** [comment]
We are planning a wide mapping table for turning NAACCR into the new Cancer Modifiers. That will take care of the numeric values kludgily encoded as codes.

**Comment by mgurley** [comment]
Closing and placing in the deep backlog to focus the repository.
