### ISSUE TITLE
Insert Treatment 'did not happen' concepts into the OBSERVATION table.

### ISSUE THREAD

**Issue by mgurley** [OHDSI/OncologyWG#73]
The vocabulary work for this task was completed in #68.

**Comment by sratwani** [comment]
Assigned to Qi Yang.

**Comment by crabcakeworld** [comment]
The script for this is pretty much done. However, one issue is pending on the community decision. Since these are "did not happen" treatment, most likely the NAACCR source data do not provide  date for these values. But Observation_date field is a required field. So what date should we put in there? Michael suggests to use date of diagnosis.  I would like to get an agreement on this from other leaders of the group.

**Comment by jeremywarner** [comment]
The decision not to treat is often made at some time later than diagnosis. For example, a patient with early stage breast cancer may undergo surgery and then decide to forego adjuvant therapy, or they may undergo surgery and adjuvant therapy and decide to forego radiation therapy, etc. In order to accommodate this “gray zone”  in the DeepPhe information model, we have adopted the concept of a medical decision making period, which is exactly as it sounds – the period of time during which the patient and provider are engaged in shared decision making (ideally) to arrive at a decision on whether or not to treat. When this period concludes, the patient enters the treatment episode or the surveillance/follow-up episode, depending on the decision.

I know this is a non-answer, but the point is that it is complicated and anchoring to the date of diagnosis risks being off by even months or years. If that is an acceptable bias, then that is probably the best path forward.

Best,
Jeremy

Jeremy L. Warner MD, MS, FAMIA
Associate Professor of Medicine and Biomedical Informatics at Vanderbilt University
Medical Director, Vanderbilt Cancer Registry
Chair, AMIA Visual Analytics Work Group
Deputy Editor, HemOnc.org

Shaina McKenzie
Lead Administrative Assistant
shaina.e.mckenzie@vumc.org
615-936-3524

**Comment by cgreich** [comment]
WEll, then let's not call it "Did not happen", but "Decision making" or so. "Did not happen" will create gazillion confusions.

But I still not get it. We have "Initial diagnosis". Why can't we continue that Episode till the treatment starts?

**Comment by jeremywarner** [comment]
In the DeepPhe episodes model, we declare that the diagnostic episode is over once all the diagnostic and staging procedures are completed. Copying Harry and Guergana in case they’d like to weigh in further about the thought process behind distinguishing this from medical decision making.

Best,
Jeremy

Jeremy L. Warner MD, MS, FAMIA
Associate Professor of Medicine and Biomedical Informatics at Vanderbilt University
Medical Director, Vanderbilt Cancer Registry
Chair, AMIA Visual Analytics Work Group
Deputy Editor, HemOnc.org

Shaina McKenzie
Lead Administrative Assistant
shaina.e.mckenzie@vumc.org
615-936-3524

**Comment by jeremywarner** [comment]
Jeremy, 

our annotation guidelines state that medical decision making includes  "Any documents that discuss potential treatments after a diagnosis has been made”. We also explicitly state that treatment and diagnosis can co-occur. Thus, it seems that we could be in a diagnosis episode until treatment starts, if there is no discussion of potential treatments.

Guergana, does that sound right?

-harry

> On Nov 11, 2019, at 10:17 PM, Warner, Jeremy <jeremy.warner@vumc.org> wrote:
> 
> In the DeepPhe episodes model, we declare that the diagnostic episode is over once all the diagnostic and staging procedures are completed. Copying Harry and Guergana in case they’d like to weigh in further about the thought process behind distinguishing this from medical decision making.
>  
> Best,
> Jeremy
>  
> Jeremy L. Warner MD, MS, FAMIA
> Associate Professor of Medicine and Biomedical Informatics at Vanderbilt University
> Medical Director, Vanderbilt Cancer Registry
> Chair, AMIA Visual Analytics Work Group
> Deputy Editor, HemOnc.org
>  
> Shaina McKenzie
> Lead Administrative Assistant
> shaina.e.mckenzie@vumc.org
> 615-936-3524
>  
>  
> From: Christian Reich <notifications@github.com>
> Reply-To: OHDSI/OncologyWG <reply@reply.github.com>
> Date: Monday, November 11, 2019 at 8:17 PM
> To: OHDSI/OncologyWG <OncologyWG@noreply.github.com>
> Cc: "Warner, Jeremy" <jeremy.warner@vumc.org>, Comment <comment@noreply.github.com>
> Subject: Re: [OHDSI/OncologyWG] Insert Treatment 'did not happen' concepts into the OBSERVATION table. (#73)
>  
> WEll, then let's not call it "Did not happen", but "Decision making" or so. "Did not happen" will create gazillion confusions.
> 
> But I still not get it. We have "Initial diagnosis". Why can't we continue that Episode till the treatment starts?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

----
Harry Hochheiser
Associate Professor, Department of Biomedical Informatics 
Associate Professor, Intelligent Systems Program 
Director, Biomedical Informatics Training Program
University of Pittsburgh
harryh@pitt.edu 		412 648 9300

**Comment by cgreich** [comment]
@jeremywarner:

Hm. I am thinking. This is a slippery slope. The OMOP CDM captures facts that happen to the patient, or in direct context of patient care. A thought process of a physician is not something that happens to a patient. So, I would suggest to omit all sorts of "Can't make up our minds" or "Considered, but decided otherwise" concepts that then are the foundation of Disease Episodes of the patient. These should define things that actually happen to the patient. They are not even flavors of NULL. 

I'd still be in favor of "Initial Diagnosis" until the treatment starts. Of course there will be more diagnostic activity, but that wouldn't be "initial" anymore.

**Comment by jeremywarner** [comment]
You are right of course (about the slippery slope).

Stepping back for a second, there are a number of NAACCR elements that are geared toward the general theme of “we suggested that the patient receive X or Y therapy, but they refused it”. These are meant to be distinguished from the “we wanted the patient to get the treatment but something happened before they could (e.g., they died)” or “we did not suggest any treatment because they are too sick to tolerate it”. All of these result in the “did not happen” phenotype but in fact they are distinctly different and can help to define very different tranches of patients. I believe such data has been used to show that elderly patients tend not to be offered treatment even when they might have tolerated it, for example. Likewise for trying to ferret out health disparities.

These are important concepts in the registry community but perhaps as you say don’t quite fit right in the OHDSI framework.

Best,
Jeremy

Jeremy L. Warner MD, MS, FAMIA
Associate Professor of Medicine and Biomedical Informatics at Vanderbilt University
Medical Director, Vanderbilt Cancer Registry
Chair, AMIA Visual Analytics Work Group
Deputy Editor, HemOnc.org

Shaina McKenzie
Lead Administrative Assistant
shaina.e.mckenzie@vumc.org
615-936-3524

**Comment by cgreich** [comment]
Usually, those are the outcomes of OHDSI type research. So, if a patient doesn't get treated or does - we capture that from the data. For example, NAACCR value 35941582 700@85 "Chemotherapy was not administered because the patient died prior to planned or recommended therapy." If we have a death record we don't need a Concept with this logical assertion. If we don't have a death record - now is the time to write one.

**Comment by rtmill** [comment]
Solution discussed on today's call: Let the domain of the value concept determine whether or not insert into measurement (meas val) or into observation (observation).

**Comment by mgurley** [comment]
What date should be placed in observation_date/observation_datetime?
